### ISSUE TITLE
Coldfire MCF5407 with external NOR flash

### ISSUE THREAD

**Issue by hinxx** [podonoghue/usbdm-firmware#11]
I have two PCBs with MCF5407 with external NOR flash. There is also a BDM 26-pin connector available. I would like to copy flash contents from one board to another. Which hardware from your project could I use?

**Comment by podonoghue** [comment]
I'm sorry I don't believe any version would be usable.
The programmers and memory dump have only been developed for internal flash programming and reading.
There is no target code written to support external memory device programming.
I don't believe memory dump would be able to read the external flash because it is necessary to configure the chip-select logic first.
